### ISSUE TITLE
so what should I actually do with this .rom file?

### ISSUE THREAD

**Issue by vejinnovem** [LIV2/lide.device#8]
Forgive me my ignorance. 
I have no idea what should I do with lide.rom.
Should I merge it with my kickstart, or this should go into some other chip?
Or maybe it should be somewhere in workbench?
I don't even know where to look for more information.

**Comment by LIV2** [comment]
Hi @vejinnovem,

There are a couple of different rom versions depending on the IDE card / accelerator used

* lide.rom is for CIDER and RIPPLE boards
* lide-atbus.rom is for AT-Bus 2008 and clones, Matze TKs etc
* lide-n2630-high/low.rom is for the N2630 accelerator

These need to be programmed into the autoconfig rom of the relevant board, if you have a RIPPLE or CIDER board this can be done by booting the lide-update.adf listed under releases

If you have an N2630 then this is done by following the documentation [here](https://github.com/jasonsbeer/Amiga-N2630/blob/main/ROMs.md)

For AT-Bus 2008 etc the lide-atbus.rom needs to be programmed into that boards ROM or Flash, making sure to fill up the whole ROM.

LIDE is not a replacement driver for A600, A1200 or A4000 IDE interfaces
